import ApacheIcon from './apache-icon.svg';
import BarracudaIcon from './barracuda-icon.svg';
import CalyptiaBird from './calyptia-bird.svg';
import CalyptiaCliIcon from './calyptia-cli.svg';
import CalyptiaDocker from './calyptia-docker.svg';
import CalyptiaIcon from './calyptia-icon.svg';
import CalyptiaLogoName from './calyptia-logo-name.svg';
import CalyptiaMiniIcon from './calyptia-mini.svg';
import CalyptiaRadar from './calyptia-radar.svg';
import CalyptiaVivoIcon from './calyptia-vivo-icon.svg';
import ChefIcon from './chef-icon.svg';
import CiscoIcon from './cisco-icon.svg';
import ConsoleIcon from './console-icon.svg';
import CriIcon from './cri-icon.svg';
import DockerIcon from './docker-icon.svg';
import FluentBitIcon from './fluent-bit-icon.svg';
import FluentdIcon from './fluentd-icon.svg';
import KubernetesIcon from './kubernetes-icon.svg';
import MySqlIcon from './mysql-icon.svg';
import NginxIcon from './nginx-icon.svg';
import SyslogIcon from './syslog-icon.svg';
import VirtualMachineIcon from './virtual-machine-icon.svg';

export const CALYPTIA_CLI_ICON = CalyptiaCliIcon;
export const FLUENTBIT_ICON = FluentBitIcon;
export const FLUENTD_ICON = FluentdIcon;
export const CALYPTIA_BIRD_ICON = CalyptiaBird;
export const CALYPTIA_DOCKER = CalyptiaDocker;
export const DOCKER_ICON = DockerIcon;
export const KUBERNETES_ICON = KubernetesIcon;
export const VIRTUAL_MACHINE_ICON = VirtualMachineIcon;
export const CALYPTIA_ICON = CalyptiaIcon;
export const CALYPTIA_RADAR = CalyptiaRadar;
export const CONSOLE_ICON = ConsoleIcon;
export const CALYPTIA_MINI_ICON = CalyptiaMiniIcon;
export const APACHE_ICON = ApacheIcon;
export const BARRACUDA_ICON = BarracudaIcon;
export const CHEF_ICON = ChefIcon;
export const CISCO_ICON = CiscoIcon;
export const CRI_ICON = CriIcon;
export const MYSQL_ICON = MySqlIcon;
export const NGINX_ICON = NginxIcon;
export const SYSLOG_ICON = SyslogIcon;
export const CALYPTIA_LOGO_NAME = CalyptiaLogoName;
export const CALYPTIA_VIVO_ICON = CalyptiaVivoIcon;
